#!/usr/bin/env node
/**
 * setup.js — First-time setup wizard
 */
'use strict';

const fs = require('fs');
const path = require('path');
const { spawnSync } = require('child_process');
const { Select, Input, Confirm, Toggle } = require('enquirer');
const pc = require('picocolors');

// When run as a dependency (npx seo-setup), write to the consumer's project root.
// When run from the cloned repo (npm run setup), __dirname/.. IS the project root.
const PKG_ROOT = path.resolve(__dirname, '..');
const isInstalledDep = __dirname.includes('node_modules');
const PROJECT_ROOT = isInstalledDep ? process.cwd() : PKG_ROOT;

const ENV_PATH = path.join(PROJECT_ROOT, '.env');
const ENV_EXAMPLE_PATH = path.join(PKG_ROOT, '.env.example');
const CONFIG_PATH = path.join(PROJECT_ROOT, 'seo-checks.json');
const CONFIG_EXAMPLE_PATH = path.join(PKG_ROOT, 'seo-checks.example.json');

// ── Utilities ─────────────────────────────────────────────────────────────────

function print(line) {
  process.stdout.write((line ?? '') + '\n');
}

const DIVIDER = pc.gray('─'.repeat(62));

function header(title) {
  print('\n' + DIVIDER);
  print('  ' + pc.bold(pc.white(title)));
  print(DIVIDER);
}

// Custom prompt options to match the cyan/pro aesthetic
const promptOptions = {
  prefix: (state) => state.status === 'submitted' ? pc.cyan(pc.bold('✓')) : pc.cyan(pc.bold('?')),
  symbols: {
    indicator: pc.cyan(pc.bold('❯')),
  }
};

function findCsvFiles(dir, maxDepth = 2, _depth = 0) {
  const results = [];
  if (_depth > maxDepth) return results;
  const SKIP = new Set(['node_modules', '.git', 'dist', 'build', '.next', '.nuxt', 'coverage', 'vendor']);
  let entries;
  try { entries = fs.readdirSync(dir, { withFileTypes: true }); } catch { return results; }
  for (const entry of entries) {
    if (SKIP.has(entry.name)) continue;
    const full = path.join(dir, entry.name);
    if (entry.isDirectory()) results.push(...findCsvFiles(full, maxDepth, _depth + 1));
    else if (entry.name.toLowerCase().endsWith('.csv')) results.push(full);
  }
  return results;
}

function parseEnv(filePath) {
  const values = {};
  if (!fs.existsSync(filePath)) return values;
  const lines = fs.readFileSync(filePath, 'utf-8').split('\n');
  for (const line of lines) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    const val = trimmed.slice(eq + 1).trim();
    values[key] = val;
  }
  return values;
}

function applyWaitForReady(waitForReady) {
  if (!fs.existsSync(CONFIG_PATH)) return false;
  let config;
  try {
    config = JSON.parse(fs.readFileSync(CONFIG_PATH, 'utf-8'));
  } catch (err) {
    print(`\n  ${pc.red('!')}  ${pc.yellow('Warning:')} Could not parse ${CONFIG_PATH}.`);
    print(`     Check your JSON for syntax errors (missing commas, etc).`);
    print(`     Original error: ${err.message}\n`);
    return false;
  }
  const templates = config.templates ?? {};
  for (const template of Object.values(templates)) {
    template.waitForReady = waitForReady;
  }
  fs.writeFileSync(CONFIG_PATH, JSON.stringify(config, null, 2) + '\n', 'utf-8');
  return true;
}

function writeEnv(values) {
  let lines = [];
  if (fs.existsSync(ENV_PATH)) {
    lines = fs.readFileSync(ENV_PATH, 'utf-8').split('\n');
  }

  const updateOrAppend = (key, value, commentLines = []) => {
    const idx = lines.findIndex(line => line.trim().startsWith(key + '='));
    if (idx !== -1) {
      lines[idx] = `${key}=${value}`;
    } else {
      if (lines.length > 0 && lines[lines.length - 1].trim() !== '') {
        lines.push('');
      }
      lines.push(...commentLines);
      lines.push(`${key}=${value}`);
    }
  };

  const hasSeoComments = lines.some(line => line.includes('Generated by npm run setup'));
  if (!hasSeoComments) {
    if (lines.length > 0 && lines[lines.length - 1].trim() !== '') lines.push('');
    lines.push('# ── SEO Guardrails Configuration ───────────────────────────────────────────');
    lines.push('# Generated by npm run setup — update any time.');
    lines.push('# .env is gitignored — never commit it.');
    lines.push('');
  }

  updateOrAppend('TEST_BASE_URL', values.TEST_BASE_URL || '', [
    '# Where Playwright sends requests (your dev server, preview, or staging URL)'
  ]);

  updateOrAppend('PROD_BASE_URL', values.PROD_BASE_URL || '', [
    '',
    '# Your canonical production domain — used for canonical matching and link classification'
  ]);

  updateOrAppend('SEO_CANONICAL_MODE', values.SEO_CANONICAL_MODE || 'production', [
    '',
    '# How your site generates canonical URLs:',
    '#   production — canonicals always point to the prod domain (most sites)',
    '#   dynamic    — canonicals reflect the current host (preview / staging environments)'
  ]);

  updateOrAppend('SEO_SAMPLE_LIMIT', values.SEO_SAMPLE_LIMIT || '', [
    '',
    '# Maximum pages tested per template in the integration suite (leave blank for no limit)'
  ]);

  updateOrAppend('SEO_LANE', values.SEO_LANE || '', [
    '',
    '# Lane filter: pr | merge | scheduled | (blank = run all checks)'
  ]);

  // Ensure file ends with a newline
  if (lines.length > 0 && lines[lines.length - 1] !== '') {
    lines.push('');
  }

  fs.writeFileSync(ENV_PATH, lines.join('\n'), 'utf-8');
}

// ── Main ──────────────────────────────────────────────────────────────────────

async function main() {
  print('\n');
  print(pc.cyan(pc.bold('  ╔══════════════════════════════════════════════════════════╗')));
  print(pc.cyan(pc.bold('  ║          SEO Guardrails — First-time Setup               ║')));
  print(pc.cyan(pc.bold('  ╚══════════════════════════════════════════════════════════╝')));
  print('');
  print('  This wizard sets up your .env and seo-checks.json.');
  print(pc.gray('  Use arrow keys to navigate and Enter to confirm.'));

  // ── Inject scripts into consumer's package.json
  if (isInstalledDep) {
    const consumerPkgPath = path.join(PROJECT_ROOT, 'package.json');
    if (fs.existsSync(consumerPkgPath)) {
      let consumerPkg;
      try {
        consumerPkg = JSON.parse(fs.readFileSync(consumerPkgPath, 'utf-8'));
      } catch (err) {
        print(`\n  ${pc.red('!')}  ${pc.yellow('Warning:')} Could not parse ${consumerPkgPath}.`);
        print(`     Check your package.json for syntax errors (missing commas, etc).`);
        print(`     Original error: ${err.message}`);
        print('     SEO scripts will not be automatically added to your package.json.\n');
        consumerPkg = null;
      }

      if (consumerPkg) {
        const SEO_SCRIPTS = {
          'seo:setup': 'seo-setup',
          'seo:configure': 'seo-configure',
          'seo:generate': 'seo-generate',
          'seo:test': 'seo-test',
          'seo:test:unit': 'seo-test --project=unit',
          'seo:test:integration': 'seo-test --project=integration',
          'seo:test:prod': 'SEO_LANE=production seo-test --project=unit --project=integration',
          'seo:test:e2e': 'seo-test --project=e2e',
          'seo:report': 'playwright show-report',
        };
        const existingScripts = consumerPkg.scripts || {};
        const toAdd = Object.entries(SEO_SCRIPTS).filter(([k]) => !existingScripts[k]);
        if (toAdd.length > 0) {
          print('');
          print('  The following scripts will be added to your package.json:');
          for (const [k, v] of toAdd) print(`    ${pc.gray(k)}: ${pc.gray(v)}`);
          print('');
          
          const confirmScripts = new Confirm({
            name: 'addScripts',
            message: 'Add SEO scripts to your package.json?',
            initial: true,
            format: (value) => (value ? 'Yes' : 'No'),
            ...promptOptions
          });

          if (await confirmScripts.run()) {
            consumerPkg.scripts = { ...existingScripts, ...Object.fromEntries(toAdd) };
            fs.writeFileSync(consumerPkgPath, JSON.stringify(consumerPkg, null, 2) + '\n', 'utf-8');
            print(`  ${pc.cyan('✓')}  Scripts added to package.json.`);
          }
        } else {
          print(`\n  ${pc.cyan('✓')}  SEO scripts already present in package.json.`);
        }
      }
    }
  }

  const existing = parseEnv(ENV_PATH);
  const exampleEnv = parseEnv(ENV_EXAMPLE_PATH);

  // ── Step 1: URLs ────────────────────────────────────────────────────────────
  header('Step 1 of 3 — URLs');
  print('');

  const prodUrlPrompt = new Input({
    message: 'Production URL (canonical domain)',
    initial: existing.PROD_BASE_URL || exampleEnv.PROD_BASE_URL || 'https://your-site.com',
    ...promptOptions
  });
  const prodUrl = await prodUrlPrompt.run();

  const testUrlPrompt = new Input({
    message: 'Test URL (where Playwright sends requests — press Enter to skip if only testing production)',
    initial: existing.TEST_BASE_URL || exampleEnv.TEST_BASE_URL || 'http://localhost:3000',
    ...promptOptions
  });
  const testUrl = await testUrlPrompt.run();

  print('');
  const canonicalModePrompt = new Select({
    message: 'How does your site generate canonical URLs?',
    choices: [
      { name: 'production', message: 'Production — canonicals always point to prod domain (Recommended)' },
      { name: 'dynamic', message: 'Dynamic — canonicals reflect the current host (localhost/preview)' }
    ],
    initial: existing.SEO_CANONICAL_MODE === 'dynamic' ? 1 : 0,
    ...promptOptions
  });
  const canonicalMode = await canonicalModePrompt.run();

  const sampleLimitPrompt = new Input({
    message: 'Page sample limit per template (recommended: 5-10)',
    initial: existing.SEO_SAMPLE_LIMIT || '5',
    ...promptOptions
  });
  const sampleLimit = await sampleLimitPrompt.run();

  print('');
  const renderingPrompt = new Select({
    message: 'Page rendering approach',
    choices: [
      { name: 'networkidle', message: 'networkidle — JS renders content after load (Safe default)' },
      { name: 'load', message: 'load — All content is in the raw server HTML (Faster)' }
    ],
    initial: 0,
    ...promptOptions
  });
  const waitForReady = await renderingPrompt.run();

  writeEnv({
    TEST_BASE_URL: testUrl,
    PROD_BASE_URL: prodUrl,
    SEO_CANONICAL_MODE: canonicalMode,
    SEO_SAMPLE_LIMIT: sampleLimit,
    SEO_LANE: '',
  });

  print(`\n  ${pc.cyan('✓')}  .env written.`);

  // ── Step 2: seo-checks.json ─────────────────────────────────────────────────
  header('Step 2 of 3 — SEO contract (seo-checks.json)');
  print('');

  let action = 'keep';
  if (fs.existsSync(CONFIG_PATH)) {
    const configActionPrompt = new Select({
      message: 'seo-checks.json already exists. What would you like to do?',
      choices: [
        { name: 'keep', message: 'Keep existing — preserves current pages and metadata' },
        { name: 'csv', message: 'Regenerate from a fresh CSV crawl' },
        { name: 'example', message: 'Reset from example JSON' }
      ],
      ...promptOptions
    });
    action = await configActionPrompt.run();
  } else {
    const creationPrompt = new Select({
      message: 'seo-checks.json not found. Choose how to create it:',
      choices: [
        { name: 'csv', message: 'Generate from CSV (Recommended — builds from actual crawl data)' },
        { name: 'example', message: 'Start from example JSON (Quick start for small sites)' }
      ],
      ...promptOptions
    });
    action = await creationPrompt.run();
  }

  if (action === 'keep') {
    print(`  ${pc.cyan('✓')}  Keeping existing seo-checks.json.`);
    applyWaitForReady(waitForReady);
  } else if (action === 'csv') {
    const csvFiles = findCsvFiles(PROJECT_ROOT);

    if (csvFiles.length === 0) {
      print(`\n  ${pc.yellow('!')} No CSV files found. Prepare one first and re-run setup.`);
      return;
    }

    const csvPrompt = new Select({
      message: 'Select a CSV file to generate from:',
      choices: [
        ...csvFiles.map(f => ({ name: f, message: path.relative(PROJECT_ROOT, f) })),
        { name: 'manual', message: 'None of these — show manual steps' }
      ],
      ...promptOptions
    });
    const selectedCsv = await csvPrompt.run();

    if (selectedCsv === 'manual') {
      print('\n  Manual steps:');
      print('     1. Export your CSV (Screaming Frog All Tabs)');
      print('     2. pip install questionary');
      print(`     3. ${pc.bold(isInstalledDep ? 'npx seo-init-config' : 'npm run init-config')}`);
      print(`     4. ${pc.bold(isInstalledDep ? 'npm run seo:generate -- your-crawl.csv' : 'npm run generate -- your-crawl.csv')}`);
      return;
    }

    // Check python3
    const pyCheck = spawnSync('python3', ['--version'], { encoding: 'utf-8' });
    if (pyCheck.error || pyCheck.status !== 0) {
      print(`\n  ${pc.red('!')} python3 not found. Install Python 3 and re-run setup.`);
      return;
    }

    const genConfigPath = path.join(PROJECT_ROOT, 'generator-config.json');
    const initScript = path.join(PKG_ROOT, 'scripts', 'init-generator-config.py');
    const generateScript = path.join(PKG_ROOT, 'scripts', 'generate-from-sf.py');

      if (!fs.existsSync(genConfigPath)) {
        const qCheck = spawnSync('python3', ['-c', 'import questionary'], { encoding: 'utf-8' });
        if (qCheck.status !== 0) {
          print(`\n  ${pc.yellow('!')} questionary required for config wizard. Run: ${pc.bold('pip install questionary')}`);
          return;
        }
        print('\n  No generator-config.json found — launching template wizard...\n');
        const initResult = spawnSync('python3', [initScript, selectedCsv, '--out', genConfigPath, '--wait-strategy', waitForReady, '--base-url', prodUrl, '--sample-limit', sampleLimit || '50'], { stdio: 'inherit', cwd: PROJECT_ROOT });
        if (initResult.status !== 0) {
          print(`\n  ${pc.red('!')}  Template wizard failed or was cancelled. Stopping setup.`);
          return;
        }
      }

    print('\n  Generating seo-checks.json...\n');
    const genResult = spawnSync('python3', [generateScript, selectedCsv, '--config', genConfigPath, '--out', CONFIG_PATH], {
      stdio: 'inherit',
      cwd: PROJECT_ROOT,
    });

    if (genResult.status !== 0) {
      print(`\n  ${pc.red('!')}  Generation failed. Please check the error messages above.`);
      return;
    }

    applyWaitForReady(waitForReady);
    print(`\n  ${pc.cyan('✓')}  seo-checks.json generated and configured.`);
  } else if (action === 'example') {
    if (fs.existsSync(CONFIG_EXAMPLE_PATH)) {
      fs.copyFileSync(CONFIG_EXAMPLE_PATH, CONFIG_PATH);
      applyWaitForReady(waitForReady);
      print(`\n  ${pc.cyan('✓')}  seo-checks.json created from example.`);
    } else {
      print(`\n  ${pc.red('!')} seo-checks.example.json not found.`);
    }
  }

  // ── Step 3: CI/CD Workflows ──────────────────────────────────────────────────
  header('Step 3 of 3 — CI/CD Workflows');
  print('');
  print('  We can generate 3 GitHub Actions workflows for continuous SEO regression testing:');
  print(`    1. ${pc.cyan('PR')}        — fast, targeted feedback when developers open Pull Requests.`);
  print(`    2. ${pc.cyan('Merge')}     — complete integration checks when code is merged to your primary branches.`);
  print(`    3. ${pc.cyan('Scheduled')} — weekly full-site crawl (E2E) to catch broken links & redirect chains over time.`);
  print('');

  const setupCIPrompt = new Confirm({
    message: 'Set up GitHub Actions workflows? (answer "No" if only testing production manually)',
    initial: true,
    format: (value) => (value ? 'Yes' : 'No'),
    ...promptOptions
  });

  if (await setupCIPrompt.run()) {
    const pushBranchesPrompt = new Input({
      message: 'Which branches should trigger SEO tests on MERGE?',
      initial: 'main, staging, dev',
      ...promptOptions
    });
    const pushBranches = (await pushBranchesPrompt.run()).split(',').map(b => b.trim()).filter(Boolean);

    const prBranchesPrompt = new Input({
      message: 'Which branches should trigger SEO tests on PR? (type "all" for any)',
      initial: 'main, staging, dev',
      ...promptOptions
    });
    const prRaw = await prBranchesPrompt.run();
    const prAll = prRaw.trim().toLowerCase() === 'all';
    const prBranches = prAll ? [] : prRaw.split(',').map(b => b.trim()).filter(Boolean);

    const includeWeeklyPrompt = new Confirm({
      message: 'Include scheduled (e.g. weekly) sitemap & link health checks?',
      initial: true,
      format: (value) => (value ? 'Yes' : 'No'),
      ...promptOptions
    });
    const includeWeekly = await includeWeeklyPrompt.run();

    print('');
    const envPrepPrompt = new Select({
      message: 'How will the CI test environment be prepared?',
      choices: [
        { name: '1', message: 'Start a local server in the workflow (e.g. npm start)' },
        { name: '2', message: 'Wait for an external deployment (e.g. Vercel, WP Engine)' },
        { name: '3', message: 'It is already running / No wait needed' }
      ],
      initial: 2,
      ...promptOptions
    });
    const envPrep = await envPrepPrompt.run();

    let serverStep = '';
    let ciTestUrl = testUrl;

    if (envPrep === '1') {
      const startCmdPrompt = new Input({ message: 'Command to start your local server in CI', initial: 'npm start', ...promptOptions });
      const startCmd = await startCmdPrompt.run();
      const waitUrlPrompt = new Input({ message: 'URL to wait for before starting tests', initial: testUrl, ...promptOptions });
      ciTestUrl = await waitUrlPrompt.run();
      serverStep = `\n      - name: Start local server\n        run: |\n          ${startCmd} &\n          npx wait-on ${ciTestUrl} --timeout 60000`;
    } else if (envPrep === '2') {
      const ciUrlPrompt = new Input({ message: 'Test URL for CI (after deployment)', initial: testUrl, ...promptOptions });
      ciTestUrl = await ciUrlPrompt.run();
      serverStep = `\n      # TODO: Add steps here to wait for your external deployment to complete.\n      # See docs/ci-integration.md#waiting-for-external-deployments for examples.`;
    } else {
      const ciUrlPrompt = new Input({ message: 'Test URL for CI', initial: testUrl, ...promptOptions });
      ciTestUrl = await ciUrlPrompt.run();
    }

    const configFlag = isInstalledDep ? '--config=node_modules/tech-seo-guardrails/playwright.config.js' : '';
    const reporterPath = isInstalledDep ? 'node_modules/tech-seo-guardrails/src/reporters/seo-summary.js' : './src/reporters/seo-summary.js';
    const selectTestsPath = isInstalledDep ? 'node_modules/tech-seo-guardrails/scripts/select-tests.sh' : 'scripts/select-tests.sh';

    let version = 'unknown';
    try {
      version = JSON.parse(fs.readFileSync(path.join(PKG_ROOT, 'package.json'), 'utf-8')).version;
    } catch (e) {
      console.error(`\n  ${pc.red('!')} Debug: Error reading version: ${e.message}`);
    }

    const vars = {
      VERSION: version,
      PUSH_BRANCHES: `[${pushBranches.join(', ')}]`,
      PR_BRANCHES_LINE: prAll ? '' : `    branches: [${prBranches.join(', ')}]`,
      CONFIG_FLAG: configFlag,
      REPORTER_PATH: reporterPath,
      SELECT_TESTS_PATH: selectTestsPath,
      SERVER_STEP: serverStep,
      TEST_BASE_URL: ciTestUrl,
      PROD_BASE_URL: prodUrl,
      SEO_CANONICAL_MODE: canonicalMode,
    };

    function renderTemplate(content, templateVars) {
      let result = `# Generated by Tech SEO Guardrails v${templateVars.VERSION}\n${content}`;
      for (const [key, value] of Object.entries(templateVars)) {
        result = result.split(`{{${key}}}`).join(value);
      }
      return result;
    }

    const workflowsDir = path.join(PROJECT_ROOT, '.github', 'workflows');
    if (!fs.existsSync(workflowsDir)) fs.mkdirSync(workflowsDir, { recursive: true });

    const templatesDir = path.join(PKG_ROOT, 'templates', 'workflows');
    const toWrite = [
      { template: 'seo-merge.yml', dest: 'seo-merge.yml', label: 'unit + integration on merge' },
      { template: 'seo-pr.yml', dest: 'seo-pr.yml', label: 'unit + scoped integration on PRs' },
      ...(includeWeekly ? [{ template: 'seo-scheduled.yml', dest: 'seo-scheduled.yml', label: 'full suite scheduled' }] : []),
    ];

    let writtenWorkflows = [];
    for (const { template, dest, label } of toWrite) {
      const templatePath = path.join(templatesDir, template);
      const destPath = path.join(workflowsDir, dest);
      if (!fs.existsSync(templatePath)) continue;

      const content = renderTemplate(fs.readFileSync(templatePath, 'utf-8'), vars);
      if (fs.existsSync(destPath)) {
        if (fs.readFileSync(destPath, 'utf-8') === content) {
          writtenWorkflows.push({ dest, label, status: 'unchanged' });
          continue;
        }
        const overwritePrompt = new Confirm({
          message: `${dest} is out of sync. Update it?`,
          initial: true,
          format: (value) => (value ? 'Yes' : 'No'),
          ...promptOptions
        });
        if (!(await overwritePrompt.run())) {
          writtenWorkflows.push({ dest, label, status: 'skipped' });
          continue;
        }
      }
      fs.writeFileSync(destPath, content, 'utf-8');
      writtenWorkflows.push({ dest, label, status: 'written' });
    }

    if (writtenWorkflows.length > 0) {
      print(`\n  ${pc.cyan('✓')}  Workflows processed in .github/workflows/:`);
      for (const { dest, label, status } of writtenWorkflows) {
        const icon = status === 'unchanged' ? pc.gray('·') : (status === 'skipped' ? pc.yellow('-') : pc.cyan('✓'));
        const msg = status === 'unchanged' ? pc.gray('(already up to date)') : label;
        print(`     ${icon} ${dest.padEnd(20)} — ${msg}`);
      }
    }
  }

  // ── Summary ─────────────────────────────────────────────────────────────────
  header('Setup Complete!');
  print(`\n  Your settings:`);
  print(`    PROD_BASE_URL       ${prodUrl}`);
  print(`    TEST_BASE_URL       ${testUrl}`);
  print(`    SEO_CANONICAL_MODE  ${canonicalMode}`);
  print(`    SEO_SAMPLE_LIMIT    ${sampleLimit || '(all pages)'}`);
  print(`    waitForReady        ${waitForReady}`);
  print(`\n  ${pc.bold('Next steps:')}`);
  print('\n  1. Edit seo-checks.json — add paths and metadata.');
  print(`  2. Fine-tune checks & severities: ${pc.bold(isInstalledDep ? 'npx seo-configure' : 'npm run configure')}`);
  print(`  3. Run tests: ${pc.bold(isInstalledDep ? 'npm run seo:test' : 'npm test')}`);
  print('\n  See README.md for the full reference.\n');
}

main().catch((err) => {
  process.stderr.write(`\n  ${pc.red('Error:')} ${err.message}\n\n`);
  process.exit(1);
});
